Crafts/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BL;
using DAL;
using BL.SharedModels;

namespace Crafts.Controllers
{
    public class CartController : Controller
    {
        BL.Product productLogic = new BL.Product();

        // GET: Cart
        public ActionResult Index()
        { 
            return View();
        }

        public ActionResult ShowProductToTest()
        {
            List<BL.SharedModels.ProductModel> testproducts = productLogic.productsForTestingCartMethods();
            ViewBag.productstest = testproducts;
            return View();
        }

        BL.Cart CartLogic = new BL.Cart();
        public PartialViewResult Add(int ID)
        {
            CartLogic.AddItemToCart(ID);
            return PartialView("_shoppingCart");
        }
        public ActionResult cartDisplay()
        {
            if (CartLogic.viewMyCart() != null)
            {
                CartModel MyCart = CartLogic.viewMyCart();
                ViewBag.cart = MyCart;
                ViewBag.CartItems = MyCart.CartItem;
                return View("cartDisplay");
            }
            else
            {
                return View("cartDisplayEmpty");

            }

        }
        public ActionResult Increase(int ID)
        {
            CartLogic.increase(ID);
            //return PartialView("_UpdateQuantityText");
            return RedirectToAction("cartDisplay");

        }
        public ActionResult Decrease(int ID)
        {
            CartLogic.decrease(ID);
            //return PartialView("_UpdateQuantityText");
            return RedirectToAction("cartDisplay");
        }
        public ActionResult checkout(int phone, string address)
        {
            Session.Add("checkOutRequest",true);
            CartModel MyCart = CartLogic.viewMyCart();
            ViewBag.cart = MyCart;
            ViewBag.CartItems = MyCart.CartItem;
            bool success = CartLogic.checkout( phone, address);
            if (success == true)
            { return View("Receipt");}
            else
            {
                return RedirectToAction("Login", "User");
            }
        }



        public ActionResult clearCart()
        {
            CartLogic.clearCart();
            return RedirectToAction("cartDisplay");

        }


    }

}

Crafts/Controllers/CategoryController.cs
using BL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Crafts.Controllers
{
    public class CategoryController : Controller
    {
 

        Category mycat = new Category();

        public ActionResult SelectedCategory(int id)
        {
            Product pro = new Product();
            ViewBag.products = pro.CategoryProducts(id);
            ViewBag.cat_id = id;
            ViewBag.catname = mycat.categoryname(id);
            if (Session["user"] != null)
            {
                ViewBag.substate = mycat.checksubscribe((int)Session["User_Id"], id);

            }

                return View();
        }

        public ActionResult showCategories()
        {
            ViewBag.Categories = mycat.AllCategories();
            return View();
        }
        [HttpPost]
        public PartialViewResult Subscribe(int user_id,int cat_id)
        {
            if (Session["user"] != null)
            {
                Product pro = new Product();
                ViewBag.products = pro.CategoryProducts(cat_id);
                Category mycat = new Category();
                mycat.Subscribe((int)Session["User_Id"], cat_id);
                return PartialView();
            }
            return PartialView("errorview");
        }

        [HttpPost]
        public PartialViewResult UnSubscribe(int user_id, int cat_id)
        {
            Product pro = new Product();
            ViewBag.products = pro.CategoryProducts(cat_id);
            Category mycat = new Category();
            mycat.UnSubscribe((int)Session["User_Id"], cat_id);
            return PartialView();
        }

    }
}

Crafts/Controllers/ProductController.cs
using BL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BL.SharedModels;

namespace Crafts.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ProductView(int id)
        {
            BL.Product proModel = new BL.Product();
            ProductModel proDuctDetails = proModel.ProductDetailsView(id);

            return View(proDuctDetails);
        }

        
    }
}

Crafts/Views/Category/Products.cshtml
@{
    ViewBag.Title = "Products";
    Layout = "~/Views/Shared/_Main.cshtml";
}

Crafts/Views/Category/SelectedCategory.cshtml
@{
    ViewBag.Title = "SelectedCategory";
    Layout = "~/Views/Shared/_Main.cshtml";
}


<section class="banner_area mt-3 pt-3">
    <div class="banner_inner d-flex align-items-center">
        <div class="container">
            <div class="banner_content text-center">

                <!-- cover image -->
            </div>
        </div>
    </div>
</section>

<!--================Category Product Area =================-->
<section class="cat_product_area section_gap">
    <div class="container-fluid">
        <div class="row flex-row-reverse">
            <div class="col-lg-9">
                
               
                    <div><h3 class=" d-block max-auto  col-6 radius x-large" id="id"> @ViewBag.catname  </h3></div>

                    <div class="latest_product_inner row">

                        @foreach (var item in ViewBag.products)
                        {
                            <div class="col-lg-3 col-md-3 col-sm-6">
                                <div class="f_p_item">
                                    <div class="f_p_img">
                                        <img class="img-fluid proimage2" src="data:image;base64,@System.Convert.ToBase64String(item.Image)" alt="">
                                        <div class="p_icon">
                                         

                                            @Ajax.ActionLink(" ", "Add", "Cart", new { ID = @item.Product_Id },
                                   new AjaxOptions
                                   {
                                       UpdateTargetId = "shoppingCartID",
                                       InsertionMode = InsertionMode.Replace,
                                       HttpMethod = "GET"
                                   },
                                   new { @class = "fas fa-cart-plus" })




                                        </div>
                                    </div>
                                    <a href="@Url.Action("ProductView","Product",new {id= @item.Product_Id })">
                                        <h4>@item.Product_Name</h4>
                                    </a>
                                    <h5>@item.Product_Price L.E</h5>
                                </div>
                            </div>

                        }




                    </div>
                </div>
            <div class="col-lg-3">
                <div class="left_sidebar_area">
                    <div class="widgets_inner"">
                        @*replace user_id=1 with Session["user"]*@
                        @using (Ajax.BeginForm("Subscribe", new { user_id = 1, cat_id = ViewBag.cat_id }, new AjaxOptions { UpdateTargetId = "msgerror", InsertionMode = InsertionMode.Replace, HttpMethod = "POST", OnComplete = "myfn" }))
                        {
                            <div id="subscribe" class="">
                                <b id="checkstate" class="text-white">@ViewBag.substate</b>
                                <input type="submit" value="Subscribe Category" class="col-10 pl-1 pr-2 btn btn-primary" />
                            </div>

                        }


                        @using (Ajax.BeginForm("Unsubscribe", new { user_id = 1, cat_id = ViewBag.cat_id }, new AjaxOptions { UpdateTargetId = "msgerror", InsertionMode = InsertionMode.Replace, HttpMethod = "POST", OnComplete = "myfn" }))
                        {
                            <div id="unsubscribe" class="">
                                <b id="" class="text-white"> @ViewBag.substate</b>
                                <input type="submit" value="UnSubscribe Category" class="col-10 pl-1 pr-2 btn btn-danger" />
                            </div>
                        }

                        <div class="widgets_inner pl-1 hide" id="error">@Session["User_Id"]
                            <a  href="@Url.Action("Login","User")" class=" genric-btn danger circle arrow">
                                 Login First 
                                <span class="lnr lnr-arrow-right"></span>
                            </a>
                        </div>

                        </div>
                    <div>

                            <aside class="left_widgets cat_widgets">
                                <div class="l_w_title">
                                    <h3>Browse Categories</h3>
                                </div>
                                <div class="widgets_inner">
                                    <ul class="list">
                                        @{Html.RenderAction("showCategories", "Category");}
                                    </ul>
                                </div>
                            </aside>
                    </div>

            </div>
        </div>

        <div class="row">
            <nav class="cat_page mx-auto" aria-label="Page navigation example">
                @*<ul class="pagination">
                    <li class="page-item">
                        <a class="page-link" href="#">
                            <i class="fa fa-chevron-left" aria-hidden="true"></i>
                        </a>
                    </li>
                    <li class="page-item active">
                        <a class="page-link" href="#">01</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="#">02</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="#">03</a>
                    </li>
                    <li class="page-item blank">
                        <a class="page-link" href="#">...</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="#">09</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="#">
                            <i class="fa fa-chevron-right" aria-hidden="true"></i>
                        </a>
                    </li>
                </ul>*@
            </nav>
        </div>
    </div>
        </div>
        </section>
<!--================End Category Product Area =================-->
<script type="text/javascript">

    var sub = document.getElementById("subscribe");
    var unsub = document.getElementById("unsubscribe");
    var checkstate = document.getElementById("checkstate");
    var error = document.getElementById("error");
    if (checkstate.innerText =="true") {
        sub.classList.add("hide")
    }
    else {
        unsub.classList.add("hide")
    }

        function myfn() {
            if ("@Session["User_Id"]" == 0) {
                error.classList.remove("hide")
                unsub.classList.add("hide")
                sub.classList.add("hide")
            }
            else {
                var subclass = sub.className;

                if (subclass == "hide") {

                    sub.classList.remove("hide")
                    unsub.classList.add("hide")
                }
                else {
                    sub.classList.add("hide")
                    unsub.classList.remove("hide")
                }
            }
        }


</script>

Crafts/Views/Category/showCategories.cshtml
@foreach (var item in ViewBag.Categories){
<li class="nav-item" >
    @Html.ActionLink((string)item.Cat_Name, "SelectedCategory", "Category", new { id = item.Cat_Id }, new { @class = "nav-link" })
</li>
}

           