Crafts/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BL;
using DAL;
using BL.SharedModels;

namespace Crafts.Controllers
{
    public class CartController : Controller
    {
        BL.Product productLogic = new BL.Product();

        // GET: Cart
        public ActionResult Index()
        { 
            return View();
        }

        public ActionResult ShowProductToTest()
        {
            List<BL.SharedModels.ProductModel> testproducts = productLogic.productsForTestingCartMethods();
            ViewBag.productstest = testproducts;
            return View();
        }

        BL.Cart CartLogic = new BL.Cart();
        public PartialViewResult Add(int ID)
        {
            CartLogic.AddItemToCart(ID);
            return PartialView("_shoppingCart");
        }
        public ActionResult cartDisplay()
        {
            if (CartLogic.viewMyCart() != null)
            {
                CartModel MyCart = CartLogic.viewMyCart();
                ViewBag.cart = MyCart;
                ViewBag.CartItems = MyCart.CartItem;
                return View("cartDisplay");
            }
            else
            {
                return View("cartDisplayEmpty");

            }

        }
        public ActionResult Increase(int ID)
        {
            CartLogic.increase(ID);
            //return PartialView("_UpdateQuantityText");
            return RedirectToAction("cartDisplay");

        }
        public ActionResult Decrease(int ID)
        {
            CartLogic.decrease(ID);
            //return PartialView("_UpdateQuantityText");
            return RedirectToAction("cartDisplay");
        }
        public ActionResult checkout(int phone, string address)
        {
            Session.Add("checkOutRequest",true);
            CartModel MyCart = CartLogic.viewMyCart();
            ViewBag.cart = MyCart;
            ViewBag.CartItems = MyCart.CartItem;
            bool success = CartLogic.checkout( phone, address);
            if (success == true)
            { return View("Receipt");}
            else
            {
                return RedirectToAction("Login", "User");
            }
        }



        public ActionResult clearCart()
        {
            CartLogic.clearCart();
            return RedirectToAction("cartDisplay");

        }


    }

}

Crafts/Controllers/HomeController.cs
using DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BL;

namespace Crafts.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            getTopPro();
            getTrendVendors();
            return View();
        }
       
        public void getTrendVendors()
        {
            BL.Vendor VendorLogic = new BL.Vendor();
            List<User_table> selectedVendor = VendorLogic.getTopTrendVendors();
            ViewBag.selectedVendor = selectedVendor;
            
        }

        public void getTopPro()
        {
            BL.Product productLogic = new BL.Product();
            List<Product_table> selectedPro = productLogic.getTopSellingProduct();
            ViewBag.selectedPro = selectedPro;
        }

        public ActionResult about()
        {
            return View();
        }

    }
}

Crafts/Controllers/ProductController.cs
using BL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BL.SharedModels;

namespace Crafts.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ProductView(int id)
        {
            BL.Product proModel = new BL.Product();
            ProductModel proDuctDetails = proModel.ProductDetailsView(id);

            return View(proDuctDetails);
        }

        
    }
}

Crafts/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BL;
using BL.SharedModels;
using DAL;
using System.IO;

namespace Crafts.Controllers
{
    public class UserController : Controller
    {
        User ul = new User();
        BL.Vendor VendorLogic = new BL.Vendor();
        BL.Product productLogic = new BL.Product();

        // GET: User
        public ActionResult Home()
        {
            if (Session["user"] != null)
            {

                ViewBag.selectedVendor = VendorLogic.getTopTrendVendors();
                ViewBag.selectedPro = productLogic.getTopSellingProduct();
                List<ProductModel> topSeller = ul.topSellerSup();
                ViewBag.topSeller = topSeller;
                ViewBag.lastAdded = ul.lastAdded();
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }
        [HttpGet]
        public ActionResult login()
        {

            return View();
        }

        public ActionResult Show_Orders()
        {
            BL.Order order = new BL.Order();
            int id = (int)Session["User_Id"];

            List<MyOrdersModel> ViewOrders = order.ShowMyOrders(id);

            return View(ViewOrders);

        }

        public ActionResult ViewDtails(int id)
        {
            BL.Order order = new BL.Order();

            List<MyOrdersModel> ViewOrdersDetails = order.ShowMyOrdersDetails(id);
            return PartialView(ViewOrdersDetails);
        }

        public ActionResult Be_Vendor(int id)
        {
            return View();
        }

        [HttpPost]
        public ActionResult VendorRegister(string FullName, int NationalId, string Bio)
        {
            User_table USer = (User_table)Session["user"];

            int id = USer.User_Id;
            BL.User user = new BL.User();
            ViewBag.message = user.Vendor_Register(FullName, NationalId, Bio, id);
            return PartialView();
        }


        [HttpPost]
        public ActionResult login(string User_Email, string Password)
        {
            User_table user = ul.login(User_Email, Password);
            if (user != null)
            {
                var base64 = Convert.ToBase64String(user.ProfilePicture);
                var ImgSRC = string.Format("data:image/gif;base64,{0}", base64);
                Session.Add("user", user);
                Session.Add("User_Id", user.User_Id);
                Session.Add("UserFullname", user.FName + " " + user.LName);
                Session.Add("User_Email", user.User_Email);
                Session.Add("ProfilePicture", ImgSRC);
                Session.Add("Rating", user.Rating);
                Session.Add("Bio", user.Bio);
                Session.Add("Gender", user.Gender);
                if (user.Type_id == 2)
                {
                    Session.Add("vendor", "vendor");
                }
                if (Session["checkOutRequest"] != null)
                {
                    return RedirectToAction("cartDisplay", "Cart");
                }
                else
                {
                    return RedirectToAction("Home", "User");
                }

            }
            else
            {
                ViewBag.NotValidUser = "User Name OR Password is Incorrect";
                return View("login");
            }

        }

        public ActionResult logout()
        {
            Session.Clear();
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public ActionResult RegisterNewUser()
        {

            return View();
        }



        [HttpPost]
        public ActionResult RegisterNewUser(UserModel newUser)

        {

            bool check_email = ul.Sign_Up_As_User(newUser);

            if (check_email == true)
            {
                Session.Add("User", ul.GetUSerID(newUser.email));
                return RedirectToAction("UserSubscribeCategories");
            }

            else
            {
                return RedirectToAction("RegisterNewUser");
            }


        }

        public ActionResult UserSubscribeCategories()

        {

            BL.Category myCategory = new Category();
            List<CategoryModel> selectedCategory = myCategory.AllCategories();
            ViewBag.selectedCategory = selectedCategory;

            return View();
        }

        [HttpPost]

        public ActionResult UserSubscribeCategorie(int[] SelectedCategories)
        {

            int userId = int.Parse(Session["User"].ToString());
            ul.putSubscribeCategories(SelectedCategories, userId);
            List<string> FollowVendor = ul.FollowVendorsSuppliedThatCategories(userId);
            ViewBag.FollowVendors = FollowVendor;

            return PartialView();
        }

        [HttpPost]
        public ActionResult AfterFollow(string[] SelectedVendors)
        {
            int userId = int.Parse(Session["User"].ToString());
            ul.RegisterFollowedVendor(SelectedVendors, userId);
            return RedirectToAction("login", "User");
        }
        //{
        //    newUser.Rating = 0;
        //    newUser.Type_id = 1;
        //    myData.User_table.Add(newUser);
        //    myData.SaveChanges();
        //    Session["userID"] = newUser.User_Id;
        //    ModelState.Clear();
        //    newUser = null;
        //}




        [HttpGet]
        public ActionResult Contact()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Contact(string name, string email, string subject, string message)
        {

            ul.addMessage(name, email, subject, message);
            ul.sendEmail(email);
            return RedirectToAction("Index", "Home");
        }

        Vendor vendorlogic = new Vendor();

        //Selected User
        public ActionResult SelectedUser(int id)
        {
            Session.Add("profileid", id);
            BL.User user = new BL.User();
            User_table selecteduser = user.GetSelectedUser(id);
            ViewBag.user_id = selecteduser.User_Id;
            Product product = new Product();
            ViewBag.VendorProducts = product.GetProductsOfvendor(id);
            ViewBag.BestSellingVendorProducts = product.BestSellingForVendor(id);

            if (Session["user"] != null)
            {
                ViewBag.substate = vendorlogic.checkfollow((int)Session["User_Id"], id);

            }

            return View(selecteduser);


        }

        public ActionResult myprofile()
        {
            if (Session["User_Id"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("login", "User");
            }
        }

        public ActionResult mycategories()
        {
            ViewBag.mycats = ul.mySubCat((int)Session["User_Id"]);
            return View();
        }

        public ActionResult mysubvendors()
        {
            ViewBag.subs = ul.myFollowedVendor((int)Session["User_Id"]);
            return View();
        }

        public ActionResult RecommendedVendors(int id)

        {
            List<int> Vendors = ul.PersonsHasSameCategory(id);
            return View();
        }
        [HttpGet]
        public PartialViewResult getposts()
        {
            int userid = int.Parse(Session["User_Id"].ToString());
            List<PostModel> posts = ul.getuserposts(userid);
            return PartialView(posts);
        }

        public PartialViewResult getprofileposts()
        {
            int profile_id = int.Parse(Session["profileid"].ToString());

            
            List<PostModel> posts = ul.getprofileposts(profile_id);
            return PartialView(posts);
        }

        public PartialViewResult getproductsreview(int product_id)
        {
             List<ReviewModel> posts = ul.getproductposts(product_id);
            return PartialView(posts);
        }

        public ActionResult Insetuserpost(string post)
        {
            int userid = int.Parse(Session["User_Id"].ToString());
            ul.Insertuserpost(post, userid);

            return RedirectToAction("getposts");
        }

        public ActionResult InsertProductreview(string post)
        {
            if (Session["User_Id"] != null){
                int userid = int.Parse(Session["User_Id"].ToString());
                ul.InsertProductreview(post, userid);

            }
            return RedirectToAction("getproductsreview");

        }
        public ActionResult Insetusercomment(string comment, int postid)
        {

            int userid = int.Parse(Session["User_Id"].ToString());
            ul.Insertusercomments(comment, userid, postid);
            return RedirectToAction("getposts");
        }

        public PartialViewResult followedUsersPosts()
        {
            int userid = int.Parse(Session["User_Id"].ToString());
            List<PostModel> posts = ul.followedUsersPosts(userid);
            return PartialView(posts);
        }

        public ActionResult Insetusercommentnewfeeds(string comment, int postid)
        {

            int userid = int.Parse(Session["User_Id"].ToString());
            ul.Insertusercomments(comment, userid, postid);
            return RedirectToAction("followedUsersPosts");
        }

    }
}

       

Crafts/Controllers/VendorController.cs
using BL;
using BL.SharedModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Crafts.Controllers
{
    public class VendorController : Controller
    {

        // GET: Vendor orders 
        // we remove v_id =1 (default value)
        public ActionResult VendorOrders(int v_id=1)
        {
            Vendor myvendor = new Vendor();
            var orders = myvendor.VendorOrdersReview(v_id);
            ViewBag.orders = orders;
            return View();
        }


        [HttpGet]
        public ActionResult Addpost()
        {
          int userid= int.Parse(Session["User_Id"].ToString());
            var cat = Vendor.allcatigories();
            ViewBag.cat = cat;
            var Approvedproduct = Vendor.ApprovedProducts( userid);
            var Pendingproduct = Vendor.pendingProducts(userid);
            ViewBag.Pendingproduct = Pendingproduct;
            var Rejectedproduct = Vendor.rejectedProducts(userid);
            ViewBag.Rejectedproduct = Rejectedproduct;
            var outofstockproducts = Vendor.outofstockProducts(userid);
            ViewBag.outofstock = outofstockproducts;
            return View(Approvedproduct);
        }

        [HttpPost]
        public ActionResult AddProduct(ProductModel newproduct, string cat_name)
        {
            int userid = int.Parse(Session["User_Id"].ToString());
            Vendor.addnewproduct(newproduct, cat_name, userid);
            return RedirectToAction("Addpost");
        }

        //Vendor submit orders 
        public ActionResult SubmitOrder(int id)
        {
            Vendor myvendor = new Vendor();
            myvendor.AcceptOrder(id);
            return RedirectToAction("VendorOrders");
        }
        public ActionResult RejectOrder(int id)
        {
            Vendor myvendor = new Vendor();
            myvendor.RejectOrder(id);
            return RedirectToAction("VendorOrders");
        }

        public PartialViewResult Search(string search,int id)
        {
            Vendor myvendor = new Vendor();
            ViewBag.orders=myvendor.SearchOrder(search, id);
            return PartialView();
        }

        Vendor vendorlogic = new Vendor();


        [HttpPost]
        public PartialViewResult follow(int vendor_id)
        {
            if (Session["user"] != null)
            {

                bool result = vendorlogic.followvendor((int)Session["User_Id"], vendor_id);
                return PartialView();
            }
            return PartialView("errorview");
        }

        [HttpPost]
        public PartialViewResult unfollow(int vendor_id)
        {
            bool result = vendorlogic.unfollowvendor((int)Session["User_Id"], vendor_id);
            return PartialView();
        }

        public PartialViewResult outofstock(int id)
        {
            Vendor myvendor = new Vendor();
            myvendor.outofstock(id);
            return PartialView();
        }
        public PartialViewResult restoreProducts(int id)
        {
            Vendor myvendor = new Vendor();
            myvendor.restoreproduct(id);
            return PartialView();
        }
        
    }

}

Crafts/Views/User/Contact.cshtml
@{
    ViewBag.Title = "Contact";
    Layout = "~/Views/Shared/_Main.cshtml";
}

<section class="banner_area mt-3 pt-3">
    <div class="banner_inner d-flex align-items-center">
        <div class="container">
            <div class="banner_content text-center">

                <!-- cover image -->
            </div>
        </div>
    </div>
</section>



<section class="contact_area p_120">
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="contact_info">
                    <div class="info_item">
                        <i class="lnr lnr-home"></i>
                        <h6>Alexandria, Egypt</h6>
                        <p>integration technology Institute (ITI)</p>
                    </div>
                    <div class="info_item">
                        <i class="lnr lnr-phone-handset"></i>
                        <h6>
                            00 (440) 9865 562
                        </h6>
                        <p>Mon to Fri 9am to 6 pm</p>
                    </div>
                    <div class="info_item">
                        <i class="lnr lnr-envelope"></i>
                        <h6>
                            support@handmade.com
                        </h6>
                        <p>Send us your inquiry anytime!</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-9">
                <form class="row contact_form" action="Contact" method="post" id="contactForm" >
                    <div class="col-md-6">
                        <div class="form-group">
                            <input type="text" class="form-control" id="name" name="name" placeholder="Enter your name" required>
                        </div>
                        <div class="form-group">
                            <input type="email" class="form-control" id="email" name="email" placeholder="Enter email address" required>
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" id="subject" name="subject" placeholder="Enter Subject" required>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <textarea class="form-control" name="message" id="message" rows="1" placeholder="Enter Message" required></textarea>
                        </div>
                    </div>
                    <div class="col-md-12 text-right">
                        <button type="submit" value="submit" class="btn submit_btn">Send Message</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

Crafts/Views/User/DisplayUserPage.cshtml
@{
    ViewBag.Title = "DisplayUserPage";
}


<div id="div1">

    <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown button
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenu">
            <button class="dropdown-item" type="button">

                @Html.ActionLink("My Orders", "Show_Orders", new { id = @ViewBag.ID })

            </button>
            <button class="dropdown-item" type="button">

                @*@Ajax.ActionLink("Register as Vendor", "Be_Vendor", new AjaxOptions { UpdateTargetId = "div1" }, new AjaxOptions { InsertionMode = InsertionMode.InsertAfter }, new { id = @ViewBag.ID })*@
                @Html.ActionLink("Register as Vendo", "Be_Vendor", new { id = @ViewBag.ID })
            </button>
            <button class="dropdown-item" type="button">

                @Html.ActionLink("Sign Out", "", new { id = @ViewBag.ID })
            </button>
        </div>
    </div>



</div>

Crafts/Views/User/SelectedUser.cshtml
@model DAL.User_table

@{
    Layout = "~/Views/Shared/_ProfileOFOthers.cshtml";
    ViewBag.Title = "SelectedUser";

}


<div class="col-lg-4">
    <div class="blog_right_sidebar">

        <aside class="single_sidebar_widget author_widget">
            @{
                var base642 = Convert.ToBase64String(@Model.ProfilePicture);
                var ImgSRC2 = string.Format("data:image/gif;base64,{0}", base642);
            }
            <img class="mt-5 author_img rounded-circle" src="@ImgSRC2" width="150px" alt="">

            <h4>@Model.User_Name</h4>
         
            <p>
                @Model.Bio
            </p>
            <div class="br"></div>
        </aside>


        <aside class="single_sidebar_widget ads_widget">

            <div class="widgets_inner">
                @using (Ajax.BeginForm("follow", "Vendor", new { vendor_id = @ViewBag.user_id }, new AjaxOptions { UpdateTargetId = "msgerror", InsertionMode = InsertionMode.Replace, HttpMethod = "POST", OnComplete = "myfn" }))
                {
                    <div id="subscribe" class="">
                        <b id="checkstate" class="text-white"> @ViewBag.substate</b>
                        <input type="submit" value="Follow @Model.FName" class="col-12 pl-1 pr-1 btn btn-primary" />
                    </div>

                }


                @using (Ajax.BeginForm("unfollow", "Vendor", new { vendor_id = @ViewBag.user_id }, new AjaxOptions { UpdateTargetId = "msgerror", InsertionMode = InsertionMode.Replace, HttpMethod = "POST", OnComplete = "myfn" }))
                {
                    <div id="unsubscribe" class="">
                        <b id="" class="text-white"> @ViewBag.substate</b>
                        <input type="submit" value="Unfollow @Model.FName" class="col-12 pl-1 pr-1 btn btn-danger" />
                    </div>
                }

                <div class="widgets_inner pl-1 hide" id="error">
                    @Session["User_Id"]
                    <a href="@Url.Action("Login","User")" class=" genric-btn danger circle arrow">
                        Login First
                        <span class="lnr lnr-arrow-right"></span>
                    </a>
                </div>
            </div>

        </aside>



    </div>
</div>
<div class="col-lg-8">
    <div class="container">
        <ul class="nav nav-tabs" id="myTab" role="tablist">

            <li class="nav-item">
                <a class="nav-link active show" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home"
                   aria-selected="true">Products</a>
            </li>


            <li class="nav-item">
                <a class="nav-link " id="posts-tab" data-toggle="tab" href="#posts" role="tab" aria-controls="home"
                   aria-selected="false">@Model.FName's Wall</a>
            </li>
        

        </ul>
        <div class="tab-content" id="myTabContent">

            <div class="tab-pane fade  active show" id="home" role="tabpanel" aria-labelledby="home-tab">




                <div class="row">
                    <div class="main_title">
                        <h3>Vendor Best Seller</h3>
                    </div>
                </div>
                <div class="row">

                    @foreach (var item in ViewBag.BestSellingVendorProducts)
                    {
                        var base64 = Convert.ToBase64String(@item.Image);
                        var ImgSRC = string.Format("data:image/gif;base64,{0}", base64);
                        <div class="col col1">
                            <div class="f_p_item">
                                <div class="f_p_img">
                                    <img class="img-fluid proimage" src="@ImgSRC" alt="">
                                    <div class="p_icon">
                                        <a href="#">
                                            <i class="far fa-heart"></i>
                                        </a>

                                        @Ajax.ActionLink(" ", "Add", "Cart", new { ID = @item.Product_Id },
                                   new AjaxOptions
                                   {
                                       UpdateTargetId = "shoppingCartID",
                                       InsertionMode = InsertionMode.Replace,
                                       HttpMethod = "GET"
                                   },
                                   new { @class = "fas fa-cart-plus" })


                                    </div>
                                </div>
                                <div class="prodec">
                                    <a href="@Url.Action("ProductView","Product",new {id= @item.Product_Id })">
                                        <h4>@item.Product_Name</h4>
                                    </a>
                                </div>

                                <h5>@item.Product_Price LE</h5>
                            </div>
                        </div>
                    }

                </div>
                <div class="row">
                    <div class="main_title">
                        <h3>Products</h3>
                    </div>
                </div>
                <div class="row">

                    @foreach (var item in ViewBag.VendorProducts)
            {
                var base64 = Convert.ToBase64String(@item.Image);
                var ImgSRC = string.Format("data:image/gif;base64,{0}", base64);
                        <div class="col col1">
                            <div class="f_p_item">
                                <div class="f_p_img">
                                    <img class="img-fluid proimage" src="@ImgSRC" alt="">
                                    <div class="p_icon">
                                        <a href="#">
                                            <i class="far fa-heart"></i>
                                        </a>

                                        @Ajax.ActionLink(" ", "Add", "Cart", new { ID = @item.Product_Id },
                                   new AjaxOptions
                                   {
                                       UpdateTargetId = "shoppingCartID",
                                       InsertionMode = InsertionMode.Replace,
                                       HttpMethod = "GET"
                                   },
                                   new { @class = "fas fa-cart-plus" })


                                    </div>
                                </div>
                                <div class="prodec">
                                    <a href="@Url.Action("ProductView","Product",new {id= @item.Product_Id })">
                                        <h4>@item.Product_Name</h4>
                                    </a>
                                </div>

                                <h5>@item.Product_Price LE</h5>
                            </div>
                        </div>
                    }

                </div>


            </div>
            <div class="tab-pane fade" id="posts" role="tabpanel" aria-labelledby="posts-tab">

                @using (Ajax.BeginForm("Insetuserpost",
                            new AjaxOptions
                            {
                                HttpMethod = "POST",
                                UpdateTargetId = "postsarearaget",
                                InsertionMode = InsertionMode.Replace
                            }))
            {
                    <div class="form-group margin-bottom-none">
                        <div class="col-sm-10 mt-2">
                            <input style="height:100px" name="post" class="form-control input-sm" placeholder="Write Here">
                        </div>
                        <div class="col-sm-2 mt-2">
                            <button type="submit" class="btn btn-primary  pull-right btn-block btn-sm">Post</button>
                        </div>
                    </div>
            }
                <div class="col-10 mt-5 pt-5" id="postsarearaget">
                    @{Html.RenderAction("getprofileposts", "User");}
                </div>
            </div>
        </div>

    </div>
</div>





<script type="text/javascript">

    var sub = document.getElementById("subscribe");
    var unsub = document.getElementById("unsubscribe");
    var checkstate = document.getElementById("checkstate");
    var error = document.getElementById("error");
    if (checkstate.innerText =="true") {
        sub.classList.add("hide")
    }
    else {
        unsub.classList.add("hide")
    }

        function myfn() {
            if ("@Session["User_Id"]" == 0) {
                error.classList.remove("hide")
                unsub.classList.add("hide")
                sub.classList.add("hide")
            }
            else {
                var subclass = sub.className;

                if (subclass == "hide") {

                    sub.classList.remove("hide")
                    unsub.classList.add("hide")
                }
                else {
                    sub.classList.add("hide")
                    unsub.classList.remove("hide")
                }
            }
        }


</script>

Crafts/Views/User/Show_Orders.cshtml
@*@{
    ViewBag.Title = "Show_Orders";
    Layout = "~/Views/Shared/_Profile.cshtml";
}*@


@model List<BL.SharedModels.MyOrdersModel>



<div id="div1" class="mb-5 pb-5">
     @*<h2 class="d-block mx-auto mb-5" > My Orders </h2>*@
    <table class="mt-5 pt-5 table table-bordered table-hover text-center">

        <thead>
            <tr>
                <th>Order No.</th>
                <th>Date</th>
                <th>Ship To</th>
                <th>Phone</th>
                <th>Order Total</th>
                <th>Order Details</th>

            </tr>
        </thead>

        <tbody style="color: #212529;">

            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.OrderId</td>
                    <td>@item.Date</td>
                    <td>@item.Address</td>
                    <td>@item.Phone</td>
                    <td>@item.Total</td>
                    <td>@Ajax.ActionLink("View", "ViewDtails",
                       new { id = @item.OrderId }, 
                       new AjaxOptions { UpdateTargetId = "div1" , HttpMethod="GET" })
                    </td>

                </tr>
            }

        </tbody>

    </table>


</div>

Crafts/Views/User/VendorRegister.cshtml
<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-4">Vendor Registeration</h1>
        <p class="lead">@ViewBag.message</p>
    </div>
</div>